x-logging: &default-logging
  driver: json-file
  options:
    max-size: ${CONTAINER_LOG_MAX_SIZE:-50m}
    max-file: '${CONTAINER_LOG_MAX_FILES:-5}'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    logging: *default-logging
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    networks:
      - land_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    logging: *default-logging
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-change-me}
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - land_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    logging: *default-logging
    privileged: true
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - land_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    logging: *default-logging
    ports:
      - '9100:9100'
    networks:
      - land_network

networks:
  land_network:
    external: true
    name: docker_land_network

volumes:
  grafana-data:
